[build]
  publish = ".output/public"
  command = "npm run generate"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable Netlify Identity for CMS authentication
[template.environment]
  NETLIFY_USE_YARN = "false"